name: chatify
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  rxdart: ^0.27.7
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  get: ^4.6.6
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_chat_bubble: ^2.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/png/
    - assets/fonts/nexa/

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa/NexaBold.otf
        - asset: assets/fonts/nexa/NexaLight.otf
